_extends: .github
repository:
  name: eslint-config-mocha
  description: Shareable config for ESLint for Mocha tests
  homepage: 'https://npm.im/@dsmjs/eslint-config-mocha'
  private: false
  topics: hacktoberfest
